config/routes.rb
Rails.application.routes.draw do
  match '/auth/pusher' => 'auth#pusher', via: :post

  root to: 'rooms#index'

  resources :chats, only: [:new, :show]
  resources :rooms, only: [:create, :index, :show]

  match '/payment' => 'rooms#delete', via: :get
end

app/models/room.rb
class Room
  def self.endpoint
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1zYXQ7dj0xIn0.eyJqdGkiOiJTS2ZjMTNkZTcxNjRhY2U5MmYwNmJhODcxNTE2YmIwYzFiLTE0MzcyNzkwNTciLCJpc3MiOiJTS2ZjMTNkZTcxNjRhY2U5MmYwNmJhODcxNTE2YmIwYzFiIiwic3ViIjoiQUNjZGE4Yjk1NTgwYzkwYWI4OTY2ZGNkNjA1NTk4MzYyNCIsIm5iZiI6MTQzNzI3OTA1NywiZXhwIjoxNDM3MzY1NDU3LCJncmFudHMiOlt7InJlcyI6Imh0dHBzOlwvXC9hcGkudHdpbGlvLmNvbVwvMjAxMC0wNC0wMVwvQWNjb3VudHNcL0FDY2RhOGI5NTU4MGM5MGFiODk2NmRjZDYwNTU5ODM2MjRcL1Rva2Vucy5qc29uIiwiYWN0IjpbIlBPU1QiXX0seyJyZXMiOiJzaXA6dGVzdGluZzEyM0BBQ2NkYThiOTU1ODBjOTBhYjg5NjZkY2Q2MDU1OTgzNjI0LmVuZHBvaW50LnR3aWxpby5jb20iLCJhY3QiOlsibGlzdGVuIiwiaW52aXRlIl19XX0.5MVbb08U-VmTSiNIXb-A-dLa0siSbxsyNnUFgCczpD4"
  end

  def self.get_all
    [
      { id: 1, name: "testing room1", description: "who this is a test", uuid: "124noi109dpwaa0921" },
      { id: 2, name: "testing room2", description: "who this is a test", uuid: "12321khoic" },
      { id: 3, name: "testing room3", description: "who this2 is a test", uuid: "12iu01naksx" },
      { id: 4, name: "testing room4", description: "who this is a test", uuid: "iuhurwe" }
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/auth_controller.rb
include PayPal::SDK::OpenIDConnect

class AuthController < ApplicationController
  protect_from_forgery except: :auth

  def pusher
    response = Pusher[params[:channel_name]].authenticate params[:socket_id],
      user_id: params[:id],
      user_info: { name: params[:name] }

    render json: response
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def new
    @room = Room.get_all.last
  end
  def show
    @room = Room.get_all.last
  end

  def connect
    @room = Room.get_all.last
  end
end

app/controllers/push_controller.rb
class PusherController < ApplicationController
  protect_from_forgery except: :auth

  def auth
    response = Pusher[params[:channel_name]].authenticate params[:socket_id],
      user_id: params[:id],
      user_info: { name: params[:name] }

    render json: response
  end
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery except: :auth

  def auth
    response = Pusher[params[:channel_name]].authenticate params[:socket_id],
      user_id: params[:id],
      user_info: { name: params[:name] }

    render json: response
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.get_all
  end

  def show
    @room = Room.get_all.last
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat/_name_prompt.html.haml
#name-prompt.modal.fade
  .modal-dialog
    %form
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %h4.modal-title What's your name?
        .modal-body
          %input.form-control{:autofocus => ""}/
        .modal-footer
          %button.btn.btn-success{:type => "submit"} Ok

app/views/chat/index.html.haml
=render 'chat/name_prompt'

#chat{"data-api-key" => Pusher.key, "data-auth-endpoint" => pusher_auth_path}
  %br/
  .video-container#remoteVideos
  %ul#allVideos.list-inline
    %li
      %video#localVideo{:autoplay => "", :muted => "muted"}
  %dl#messages.dl-horizontal

app/views/chats/_name_prompt.html.haml
#name-prompt.modal.fade
  .modal-dialog
    %form
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %h4.modal-title What's your name?
        .modal-body
          %input.form-control{:autofocus => ""}
        .modal-footer
          %button.btn.btn-success{:type => "submit"} Ok

app/views/chats/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>PusherTC</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <link rel="stylesheet" href="application.css"
    <script src="application.js">
</head>

<body id="controller.controller_name" class="controller.action_name">
    <div class="wrapper">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="button navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="/">PusherTC</a></div>
                <div class="collapse navbar-collapse">
                    <form class="navbar-form navbar-right" id="send-message">
                        <div class="form-group">
                            <input class="form-control" id="message" />
                        </div>
                        <button class="btn btn-success" type="submit">Send Message</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="modal fade" id="name-prompt">
                <div class="modal-dialog">
                    <form>
                        <div class="modal-content">
                            <div class="modal-header">
                                <button class="close" data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title">What's your name?</h4></div>
                            <div class="modal-body">
                                <input autofocus="" class="form-control" />
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-success" type="submit">Ok</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div id="chat"></div> //chat data-api-key=Pusher.key data-auth-endpoint=pusher_auth_path
            <br />
            <div id="remoteVideos"></div>
            <ul class="list-inline" id="allVideos">
                <li>
                    <video autoplay="" id="localVideo" muted="muted"></video>
                </li>
            </ul>
            <dl class="dl-horizontal" id="messages"></dl>
        </div>
    </div>
</body>

</html>

app/views/chats/new.html.haml
=render 'chats/name_prompt'

%div{"ng-controller" => "ChatCtrl"}
  #chat{"data-api-key" => Pusher.key, "data-auth-endpoint" => auth_pusher_path}
    %br/
    .video-overlay
      .center-div
        %form.form-inline.open-chat-group
          %input.form-control{:type=>"text", :placeholder => "$ Bounty"}
          %button#enter-btn.btn.btn-success{:type => "submit" } Enter Room

    .video-container#remoteVideos
    %ul#allVideos.list-inline{"data-access-token" => @room[:endpoint]}
      %canvas#drawing-canvas
      %li
    %dl#messages.dl-horizontal
= javascript_include_tag 'connect_chat'

app/views/chats/show.html.haml
=render 'chats/name_prompt'

%div{"ng-controller" => "ChatCtrl"}
  #chat{"data-api-key" => Pusher.key, "data-auth-endpoint" => auth_pusher_path}
    %br/
    .video-overlay
      .center-div
        %form.form-inline.open-chat-group
          %h3{:style => 'color:white;'} Waiting For Connection...
    .video-container#remoteVideos
    %ul#allVideos.list-inline{"data-access-token" => @room[:endpoint]}
      %canvas#drawing-canvas
      %li
    %dl#messages.dl-horizontal

= javascript_include_tag 'start_chat'

app/views/layouts/application.html.haml
%html
  %head
    %title= 'Vidhelp'
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %meta{content: "IE=Edge", :'http-equiv' => 'x-ua-compatible'}
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'https://js.braintreegateway.com/v2/braintree.js'
    = javascript_include_tag 'https://media.twiliocdn.com/sdk/rtc/js/v0.8/twilio-rtc-conversations.min.js'
    = javascript_include_tag 'application'
    %script{:src => "https://cdn.firebase.com/js/client/2.2.1/firebase.js"}

  %body{"ng-app" => 'starter'}
    #container
      = render 'main/topbar'
      = yield

app/views/main/_topbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'logo' do
        = image_tag 'vidhelp-logo.png', height: '40px'
    .collapse.navbar-collapse
      #colorholder
      %form.navbar-form.navbar-right
        %a.user-name Jason Shim
        = link_to "Create Chat", chat_path(123212312), id: 'start-chat', class: 'btn btn-success'
        = link_to "End Chat", '/payment', id: 'end-chat', class: 'btn btn-danger hidden'
        %button#clear-drawing.btn.btn-default.hidden{:type => "button"} Clear

app/views/rooms/index.html.haml
.hero.banner
  %h1.hero-text What do you need help with?
.container
  .row.top-spacing
    .col-sm-offset-2.col-xs-12.col-sm-2.category-tile.laundry
      .black-overlay
        %h2.hero-text Appliance Repair
    .col-xs-12.col-sm-2.category-tile.basement
      .black-overlay
        %h2.hero-text Basement Renovation
    .col-xs-12.col-sm-2.category-tile.carpet
      .black-overlay
        %h2.hero-text Carpet Cleaning
  .row.top-spacing
    .col-sm-offset-2.col-xs-12.col-sm-2.category-tile.duct
      .black-overlay
        %h2.hero-text Duct Cleaning
    .col-xs-12.col-sm-2.category-tile.hard-hat
      .black-overlay
        %h2.hero-text General Contractors
    .col-xs-12.col-sm-2.category-tile.heating
      .black-overlay
        %h2.hero-text Heating & Air Conditioning
  .row.top-spacing
    .col-sm-offset-2.col-xs-12.col-sm-2.category-tile.plumbing
      .black-overlay
        %h2.hero-text Plumbing
    .col-xs-12.col-sm-2.category-tile.roofing
      .black-overlay
        %h2.hero-text Roofing
    .col-xs-12.col-sm-2.category-tile.door
      .black-overlay
        %h2.hero-text Window & Door Installation
  .row.top-spacing


:javascript
  $('.category-tile').click( function() {
     location.href='/chats/new';
  });